### ISSUE TITLE
Absence of required argument in method def causes JS error

### ISSUE THREAD

**Issue by tansaku** [makersacademy/apply#12]
``` ruby
def random_name(string)
  string
end

puts "Hello, #{random_name}"
```

gives 

```
TypeError: Cannot read property '$==' of undefined
    at block (http://interviews.makersacademy.com/javascripts/all.js:10150:60)
    at Opal.yieldX (http://interviews.makersacademy.com/javascripts/all.js:6985:18)
    at self.$each.$$p (http://interviews.makersacademy.com/javascripts/all.js:10158:26)
    at Opal.yield1 (http://interviews.makersacademy.com/javascripts/all.js:6965:14)
    at Array.def.$each.TMP_6 [as $each] (http://interviews.makersacademy.com/javascripts/all.js:12609:26)
    at Array.Opal.defn.TMP_7 [as $count] (http://interviews.makersacademy.com/javascripts/all.js:10170:12)
    at eval (eval at <anonymous> (http://interviews.makersacademy.com/javascripts/all.js:33091:19), <anonymous>:45:28)
    at eval (eval at <anonymous> (http://interviews.makersacademy.com/javascripts/all.js:33091:19), <anonymous>:50:3)
    at $Apply.def.$eval_code (http://interviews.makersacademy.com/javascripts/all.js:33091:14)
    at $Apply.def.$run_code (http://interviews.makersacademy.com/javascripts/all.js:33077:25)

```

**Comment by tansaku** [comment]
seems like a middleman upgrade is required ... https://github.com/opal/opal/issues/1287
